import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import Header from "./header";
import Footer from "./footer";

const ubuntu = Ubuntu({
  weight: [ "300", "400", "700" ],
  subsets: ["latin"],
});

const root = "localhost:3000/"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className} bg-gray-100`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
